-- MySQL Script generated by MySQL Workbench
-- Sun May 19 13:35:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbCarteiraVacina
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `dbCarteiraVacina` DEFAULT CHARACTER SET utf8;
USE `dbCarteiraVacina`;

-- -----------------------------------------------------
-- Table `Conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conta` (
  `id_Conta` INT NOT NULL AUTO_INCREMENT,
  `senha` VARCHAR(12) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_Conta`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cadastro` (
  `CPF` VARCHAR(11) NOT NULL,
  `docSUS` VARCHAR(15) NULL,
  `nome` VARCHAR(45) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `Conta_id_Conta` INT NOT NULL,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF`),
  UNIQUE INDEX `docSUS_UNIQUE` (`docSUS`),
  PRIMARY KEY (`CPF`, `Conta_id_Conta`),
  INDEX `fk_Cadastro_Conta1_idx` (`Conta_id_Conta`),
  CONSTRAINT `fk_Cadastro_Conta1`
    FOREIGN KEY (`Conta_id_Conta`)
    REFERENCES `Conta` (`id_Conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `CarteiraVacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarteiraVacina` (
  `id_CarteiraVacina` INT NOT NULL AUTO_INCREMENT,
  `foto` BLOB NULL,
  `fk_Cadastro_CPF` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_CarteiraVacina`, `fk_Cadastro_CPF`),
  INDEX `fk_CarteiraVacina_Cadastro1_idx` (`fk_Cadastro_CPF`),
  CONSTRAINT `fk_CarteiraVacina_Cadastro1`
    FOREIGN KEY (`fk_Cadastro_CPF`)
    REFERENCES `Cadastro` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ListaVacinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ListaVacinas` (
  `id_ListaVacinas` INT NOT NULL AUTO_INCREMENT,
  `DescricaoVacina` VARCHAR(45) NOT NULL,
  `Vacina` VARCHAR(45) NOT NULL,
  `QuantDose` INT NOT NULL,
  `DataParaVacinar` INT NOT NULL,
  PRIMARY KEY (`id_ListaVacinas`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `VacinasTomadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VacinasTomadas` (
  `fk_id_ListaVacinas` INT NOT NULL,
  `fk_id_CarteiraVacina` INT NOT NULL,
  `doseTomadas` INT NOT NULL,
  PRIMARY KEY (`fk_id_ListaVacinas`, `fk_id_CarteiraVacina`),
  INDEX `fk_VacinasTomadas_ListaVacinas1_idx` (`fk_id_ListaVacinas`),
  INDEX `fk_VacinasTomadas_CarteiraVacina1_idx` (`fk_id_CarteiraVacina`),
  CONSTRAINT `fk_VacinasTomadas_ListaVacinas1`
    FOREIGN KEY (`fk_id_ListaVacinas`)
    REFERENCES `ListaVacinas` (`id_ListaVacinas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VacinasTomadas_CarteiraVacina1`
    FOREIGN KEY (`fk_id_CarteiraVacina`)
    REFERENCES `CarteiraVacina` (`id_CarteiraVacina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
